services:

  api:
    build:
      context: .
      dockerfile: WebAppTemplate.API/Dockerfile

    ports:
      - "5000:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__myConn: "Server=sqlserver,1433;Database=TestTemplateDb;User Id=sa;Password=Matech321@;TrustServerCertificate=True;"

    depends_on:
      sqlserver:
        condition: service_healthy

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Matech321@"

    ports:
      - "1433:1433"

    healthcheck:
      test: ["CMD-SHELL", "grep -q 'SQL Server is now ready for client connections' /var/opt/mssql/log/errorlog || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 24
      start_period: 30s
